name: test

on:
  push:
    paths:
      - '**.go'
    tags-ignore:
      - v*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3

      - name: Run tests
        run: go test -v -cover -timeout=30s ./...
